# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Generated Dockerfile for Tibber MCP Server
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock server.py .
COPY README.md LICENSE consumption_analysis.md ./
COPY doc ./doc

# Install dependencies
RUN pip install --no-cache-dir httpx>=0.28.1 mcp[cli]>=1.5.0 pytibber>=0.30.8

# Default transport
ENV MCP_TRANSPORT=stdio

# Default command
ENTRYPOINT ["python", "server.py"]
